[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "cd frontend && npm run dev"
  targetPort = 5173
  port = 8888

