[build]
  base = "frontend/online-doctor-main"
  command = "npm install && npm run build"
  publish = "dist"   # relative to base, so no need to repeat full path

[functions]
  directory = "functions"

[template.environment]
  GROQ_API_KEY = "Set this in Netlify dashboard (Site Settings → Environment variables)"

